name: Build Android

on:
  push:
    branches:
      - deployment-workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Install dependencies
        run: npm install

      - name: Build Android
        run: |
          cd android
          ./gradlew assembleRelease

      - name: Upload Android Artifact
        uses: actions/upload-artifact@v2
        with:
          name: android-release
          path: android/app/build/outputs/apk/release/OneVoiceEcho.apk
